version: '3.8'

services:
  b2b_api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: b2b_api_test
    environment:
      SA_PASSWORD: Strong_password_123!
      ACCEPT_EULA: Y
    volumes:
      - ./containers/database:/var/lib/mssql/data
    ports:
      - "2023:1433"
    networks:
      - app-network
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq_test
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5345:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge